default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

production:
  <<: *default
  database: dgidb_v5_prod
  host: <%= ENV.fetch("DB_HOST") { "localhost" }%>

development:
  <<: *default
  database: dgidb_v5_dev
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>

test:
  <<: *default
  database: dgidb_v5_test
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
