default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

production:
  <<: *default
  database: dgidb
  host: <%= ENV.fetch("RDS_HOSTNAME") { "localhost" } %>
  port: <%= ENV.fetch("RDS_PORT") { "5432" } %>
  username: <%= ENV.fetch("RDS_USERNAME") { "dgidb" } %>
  password: <%= ENV.fetch("RDS_PASSWORD") { "" } %>

staging:
  <<: *default
  database: dgidb
  host: <%= ENV.fetch("RDS_HOSTNAME") { "localhost" } %>
  port: <%= ENV.fetch("RDS_PORT") { "5432" } %>
  username: <%= ENV.fetch("RDS_USERNAME") { "dgidb" } %>
  password: <%= ENV.fetch("RDS_PASSWORD") { "" } %>

development:
  <<: *default
  database: dgidb
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>

test:
  <<: *default
  database: dgidb_test
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  <% if ENV['CI_BUILD'] %>
  username: postgres
  password: 'ci'
  <% end %>
