default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  encoding: unicode
  database: dgidb_v5
  host: localhost

test:
  <<: *default
  encoding: unicode
  database: dgidb_v5_test
  host: localhost
