source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "~>3.1.0"
gem "rack-cors"

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem "rails", "~> 6.1.3", ">= 6.1.3.1"
gem "pg", "~>1.2.3"
# Use Puma as the app server
gem "puma" #, '~> 5.0', '>= 5.6.4'
gem "rufo"

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

gem "graphql", "~> 1.12.15"
gem "graphql-batch", "~> 0.4.3"
gem "graphiql-rails", "~> 1.7.0"
gem "search_object_graphql", "0.3.1"
gem "sidekiq"
gem "sidekiq-cron"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", ">= 1.4.4", require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

# Security vulnerability stuff
gem "actionpack", ">= 6.1.4.6"
gem "activestorage", ">= 6.1.4.7"
gem "nokogiri", ">= 1.13.2"

# Importer dependencies
gem "graphql-client"
gem "ruby-progressbar"
gem "sqlite3", require: false
gem "zlib", require: false
gem "net-ftp", require: false
gem "rubyzip", require: false

# loading workaround until we update rails to 7
gem "net-smtp", require: false
gem "net-imap", require: false
gem "net-pop", require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "rspec-rails", "~> 5.1"
  gem "factory_bot", "~> 6.2"
end

group :development do
  gem "listen", "~> 3.3"
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem "spring"
  gem "rack-mini-profiler"

  gem "capistrano"
  gem "capistrano-rails"
  gem "capistrano-rbenv"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
