source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "~>3.1.0"
gem "rack-cors"

gem "rails", "~> 6.1.3", ">= 6.1.3.1"
gem "pg", "~>1.2.3"
gem "puma"
gem "rufo"

gem "graphql", "~> 1.12.15"
gem "graphql-batch", "~> 0.4.3"
gem "graphiql-rails", "~> 1.7.0"
gem "search_object_graphql", "0.3.1"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", ">= 1.4.4", require: false

# Background job processing
gem 'sidekiq', '~> 7.1.2'

# versions pinned for security vulnerability reasons
gem "actionpack", ">= 6.1.4.6"
gem "activestorage", ">= 6.1.4.7"
gem "nokogiri", ">= 1.13.2"

# Importer dependencies
gem "graphql-client"
gem "ruby-progressbar"
gem "sqlite3", require: false
gem "zlib", require: false
gem "net-ftp", require: false
gem "rubyzip", require: false

# loading workaround until we update rails to 7
gem "net-smtp", require: false
gem "net-imap", require: false
gem "net-pop", require: false

# required for ssh tasks
gem 'ed25519'
gem 'bcrypt_pbkdf'

group :development, :test do
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "rspec-rails", "~> 5.1"
  gem "factory_bot", "~> 6.2"
end

group :development do
  gem "listen", "~> 3.3"
  gem "spring"
  gem "rack-mini-profiler"

  gem "capistrano"
  gem "capistrano-rails"
  gem "capistrano-rbenv"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
