source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "4.0.3"
gem "rack-cors"

gem "rails", "~> 8.1.3"
gem "pg", "~> 1.6"
gem "puma", "~> 7.2"
gem "rufo"
gem "propshaft"

gem "graphql", "~> 2.6"
gem "graphql-batch", "~> 0.6.1"
gem "graphiql-rails", "~> 1.10"
gem "search_object_graphql", "~> 1.0.5"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", ">= 1.4.4", require: false

# version pinned for security vulnerability reasons
gem "nokogiri", ">= 1.13.2"

# Importer dependencies
gem "graphql-client", "~> 0.26"
gem "ruby-progressbar"
gem "csv"
gem "sqlite3", require: false
gem "zlib", require: false
gem "net-ftp", require: false
gem "rubyzip", require: false

# required for ssh tasks
gem "ed25519"
gem "bcrypt_pbkdf"

group :development, :test do
  gem "debug", platforms: [:mri, :windows]
  gem "rspec-rails", "~> 8.0"
  gem "factory_bot", "~> 6.2"
  gem "capybara"
end

group :development do
  gem "listen", "~> 3.3"
  gem "rack-mini-profiler"

  gem "capistrano"
  gem "capistrano-rails"
  gem "capistrano-rbenv"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:windows, :jruby]
