module Genome
    module Normalizers
      class GeneClaimType

        def self.name_normalizer(val)
        val = val.downcase.strip

        case val
        when 'abc transporter'
            'abc transporter'
        when 'b30_2 spry domain'
            'b30_2 spry domain'
        when 'cell surface'
            'cell surface'
        when 'clinically actionable'
            'clinically actionable'
        when 'cytochrome p450'
            'cytochrome p450'
        when 'dna directed rna polymerase'
            'dna directed rna polymerase'
        when 'dna repair'
            'dna repair'
        when 'drug resistance'
            'drug resistance'
        when 'druggable genome'
            'druggable genome'
        when 'enzyme'
            'enzyme'
        when 'exchanger'
            'exchanger'
        when 'external side of plasma membrane'
            'external side of plasma membrane'
        when 'fibrinogen'
            'fibrinogen'
        when 'g protein coupled receptor'
            'g protein coupled receptor'
        when 'growth factor'
            'growth factor'
        when 'histone modification'
            'histone modification'
        when 'hormone activity'
            'hormone activity'
        when 'ion channel'
            'ion channel'
        when 'kinase'
            'kinase'
        when 'lipase'
            'lipase'
        when 'lipid kinase'
            'lipid kinase'
        when 'methyl transferase'
            'methyl transferase'
        when 'myotubularin related protein phosphatase'
            'myotubularin related protein phosphatase'
        when 'neutral zinc metallopeptidase'
            'neutral zinc metallopeptidase'
        when 'nuclear hormone receptor'
            'nuclear hormone receptor'
        when 'phosphatidylinositol 3 kinase'
            'phosphatidylinositol 3 kinase'
        when 'phospholipase'
            'phospholipase'
        when 'protease'
            'protease'
        when 'protease inhibitor'
            'protease inhibitor'
        when 'protein phosphatase'
            'protein phosphatase'
        when 'pten family'
            'pten family'
        when 'rna directed dna polymerase'
            'rna directed dna polymerase'
        when 'serine threonine kinase'
            'serine threonine kinase'
        when 'short chain dehydrogenase reductase'
            'short chain dehydrogenase reductase'
        when 'thioredoxin'
            'thioredoxin'
        when 'transcription factor'
            'transcription factor'
        when 'transcription factor binding'
            'transcription factor binding'
        when 'transcription factor complex'
            'transcription factor complex'
        when 'transporter'
            'transporter'
        when 'tumor suppressor'
            'tumor suppressor'
        when 'tyrosine kinase'
            'tyrosine kinase'
        end
        end

    end
end
end