name: Frontend checks
on:
  pull_request:
    branches-ignore:
      - main
      - dev
      - staging
jobs:
  test_build:
    name: Test client build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: yarn install
      - name: build
        run: |
          CI=false
          yarn build
  lint:
    name: Lint client files
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: yarn --prefer-offline
      - name: Prettier check
        uses: yarn run prettier-check

